# Alembic Configuration

# The generic mechanism used here is set to assume a PostgreSQL database
sqlalchemy.url = 

# Output "encoding" used when revision files
# are written from script.py.mako
# encoding = utf-8

# path to migration files
script_location = alembic

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present missing changes
prepend_sys_path = .

# timezone to use when rendering the timestamp
# (leave empty for localtime)
# timezone =

# max length of objects name in generated migration files
# When set to None SQLALCHEMY_DISPLAY_ALT_NAME environment variable is ignored
# if False then the legacy behavior is preserved
# sqlalchemy.compare_type = false

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
